<h1>Create User</h1>

<form method="post" action="/users/save">

    <div class="form-group">
        <label for="firstname">First name</label>
        <input type="text" class="form-control" name="firstname" id="firstname" required>
    </div>
    <div class="form-group">
        <label for="lastname">Last name</label>
        <input type="text" class="form-control" name="lastname" id="lastname" required>
    </div>
    <div class="form-group">
        <label for="email">E-Mail</label>
        <input type="email" class="form-control" name="email" id="email" required>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Create">
        <a href="/users" class="btn btn-secondary">Cancel</a>
    </div>
</form>