<h1>Edit User &quot;<?= $this->user->firstname; ?> <?= $this->user->lastname; ?>&quot;</h1>

<form method="post" action="/users/save">

    <input type="hidden" name="userid" value="<?= $this->user->id; ?>">

    <div class="form-group">
        <label for="firstname">First name</label>
        <input type="text" value="<?= $this->user->firstname; ?>" class="form-control" name="firstname" id="firstname" required>
    </div>
    <div class="form-group">
        <label for="lastname">Last name</label>
        <input type="text" value="<?= $this->user->lastname; ?>" class="form-control" name="lastname" id="lastname" required>
    </div>
    <div class="form-group">
        <label for="email">E-Mail</label>
        <input type="email" value="<?= $this->user->email; ?>" class="form-control" name="email" id="email" required>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Save">
        <a href="/users" class="btn btn-secondary">Cancel</a>
    </div>
</form>